import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    // Navigation
    nav: {
      home: 'Accueil',
      destinations: 'Destinations',
      about: 'À propos',
      contact: 'Contact',
      home_desc: "L'Aventure en Terre d'Éburnie",
      destinations_desc: "Catalogue officiel & circuits",
      about_desc: "Notre histoire & guides locaux",
      contact_desc: "Devis sur-mesure & conciergerie",
      vip_concierge: "Conciergerie & Tourisme VIP",
      main_nav: "Navigation Principale",
      chat_whatsapp: "Discuter avec un conseiller (WhatsApp 24/7)",
      season_open: "Saison 2026/2027 ouverte 🇨🇮",
      current: "Actuel",
      time_prefix: "Abidjan GMT :",
    },
    // Hero
    hero: {
      title_p1: "L'Aventure Vous Attend en",
      title_p2: "Terre d'Éburnie",
      subtitle: "Explorez la Côte d'Ivoire avec nos guides passionnés et circuits d'exception. Des lagunes scintillantes d'Abidjan aux plages dorées d'Assinie, en passant par les cascades de Man et les maquis animés.",
      cta: "Commencer l'Aventure",
      swipe_hint: "Faites glisser pour explorer les destinations",
    },
    // Who We Are
    who_we_are: {
      tag: "Qui Sommes-Nous",
      headline: "Née d'une passion authentique, notre mission est de révéler toute la splendeur de la Terre d'Éburnie. Aujourd'hui, nous sommes la référence des voyages et expéditions d'exception en Côte d'Ivoire.",
      learn_more: "En Savoir Plus",
      stat1_num: "5 000+",
      stat1_label: "Voyageurs Émerveillés",
      stat2_title: "Expéditions Nature en Terre d'Éburnie",
      stat3_num: "100%",
      stat3_label: "Satisfaction Garantie",
    },
    // Popular Destinations
    popular: {
      tag: "Destinations",
      title: "Destinations les Plus Populaires",
      view_all: "Voir Toutes les Destinations",
      places_visited: "Lieux Visités",
      abidjan_badge: "Abidjan",
      abidjan_title: "Lagune Ébrié & Plateau",
      abidjan_places: "05 Lieux Visités",
      yamoussoukro_badge: "Yamoussoukro",
      yamoussoukro_title: "Basilique Notre-Dame de la Paix",
      yamoussoukro_places: "03 Lieux Visités",
      assinie_badge: "Assinie-Mafia",
      assinie_title: "Plages & Cocoteraies d’Assinie",
      assinie_places: "04 Lieux Visités",
    },
    // Adventures
    adventures: {
      tag: "Circuits & Évasions",
      title: "Aventures & Expéditions Signature",
      coverflow_title: "Qu'est-ce que vous voulez faire ?",
      item_0_title: "Trek en Jungle Tropicale",
      item_0_sub: "Mont Tonkpi & Cascades de Man",
      item_1_title: "Bivouac & Nuit Étoilée",
      item_1_sub: "Campement Nature Authentique",
      item_2_title: "Balade en Pirogue sur la Lagune",
      item_2_sub: "Eaux Calmes d’Assinie",
      item_3_title: "Survol & Panorama Aérien",
      item_3_sub: "Vues Célestes d’Éburnie",
      item_4_title: "Safari Coucher de Soleil",
      item_4_sub: "Faune & Savane Dorée",
      item_5_title: "Grand-Bassam Historique",
      item_5_sub: "Cité Balnéaire & Patrimoine UNESCO",
    },
    // Reviews
    reviews: {
      tag: "Avis Voyageurs",
      title_1: "Ce que nos voyageurs disent",
      title_2: "de leur aventure en Côte d'Ivoire",
      verified_count: "+1 250 avis vérifiés de voyageurs",
      cat_all: "Tous les avis",
      cat_lagoon: "Plages & Lagunes",
      cat_nature: "Montagnes & Nature",
      cat_culture: "Culture & Patrimoine",
      verified: "Expérience vérifiée",
      cta: "Réserver Votre Propre Aventure",
      r1_date: "Il y a 2 semaines",
      r1_circuit: "Escapade Assinie & Lagune Aby",
      r1_text: "Un séjour tout simplement magique ! La balade en pirogue à Assinie au coucher du soleil et l'accueil chaleureux des Ivoiriens nous ont profondément touchés. L'équipe d'Akwaba Tours s'est occupée de tout avec un niveau de soin et de professionnalisme irréprochable.",
      r2_date: "Il y a 3 semaines",
      r2_circuit: "Trek Mont Tonkpi & Cascades de Man",
      r2_text: "Revisiter la Terre d'Éburnie avec des guides locaux aussi passionnés a été une révélation. La traversée du pont de lianes sacré et le lever de soleil brumeux sur les collines de Man resteront gravés dans nos mémoires pour toujours. Organisation 10/10 !",
      r3_date: "Il y a 1 mois",
      r3_circuit: "Basilique & Splendeurs de Yamoussoukro",
      r3_text: "La visite de la Basilique Notre-Dame de la Paix était grandiose, et que dire des soirées dégustation en maquis autour d'un authentique Garba et d'alloco frais ! Une immersion 100% authentique, sécurisée et chaleureuse. On reviendra sans hésiter.",
      r4_date: "Il y a 3 semaines",
      r4_circuit: "Patrimoine & Quartier France à Bassam",
      r4_text: "Le charme intemporel de Grand-Bassam nous a conquis. Visiter les bâtisses coloniales du Quartier France avec un guide local passionné et déjeuner face aux rouleaux de l'Atlantique était une expérience culturelle sublime.",
    },
    // FAQ
    faq: {
      tag: "Foire Aux Questions",
      title_1: "Questions",
      title_2: "Fréquentes",
      subtitle: "Des réponses claires et précises aux interrogations les plus fréquentes pour préparer sereinement votre aventure en Côte d’Ivoire.",
      help_title: "Une question particulière ?",
      help_sub: "Échangez avec nos experts ivoiriens",
      whatsapp_btn: "WhatsApp",
      custom_prompt: "Vous préparez un voyage en groupe ou un séjour sur-mesure ?",
      custom_cta: "Demander un devis personnalisé",
      q1: "Faut-il un visa pour voyager en Côte d’Ivoire ?",
      a1: "Oui, pour la plupart des voyageurs hors CEDEAO. La démarche est très rapide : une demande d'e-Visa s'effectue en ligne (sur le site officiel snedai.com). Vous recevez votre pré-approbation par email sous 48h, et votre visa biométrique vous est délivré dès votre atterrissage à l'Aéroport International Félix-Houphouët-Boigny d'Abidjan.",
      q2: "Quels sont les vaccins obligatoires avant le départ ?",
      a2: "Le vaccin contre la fièvre jaune est strictement obligatoire et exigé dès l’atterrissage avec votre carnet de vaccination international jaune. Un traitement préventif antipaludique ainsi que des lotions anti-moustiques adaptées aux zones tropicales sont également vivement conseillés.",
      q3: "Quelle est la meilleure période pour visiter la Terre d’Éburnie ?",
      a3: "La grande saison sèche, de novembre à avril, offre un ensoleillement idéal pour profiter des plages bordées de cocotiers d’Assinie et faire des randonnées dans les montagnes verdoyantes de Man. Le climat reste agréable et chaud toute l’année avec une richesse culturelle permanente.",
      q4: "Quelle monnaie utilise-t-on et comment s’effectuent les paiements ?",
      a4: "La monnaie officielle est le Franc CFA (XOF). Les cartes bancaires internationales (Visa, Mastercard) sont acceptées dans les grands hôtels et restaurants d’Abidjan. Pour le quotidien, les marchés et les transports, les espèces et le paiement mobile (Wave, Orange Money) sont rois.",
      q5: "Comment se déroulent les circuits et le transport sur place ?",
      a5: "Tous nos déplacements s’effectuent à bord de véhicules récents, climatisés et assurés tous risques, conduits par des chauffeurs locaux chevronnés. Vous êtes accompagnés par des guides certifiés et passionnés, avec une conciergerie locale dédiée disponible 24h/24 et 7j/7.",
      q6: "Est-il possible de personnaliser un itinéraire 100% sur-mesure ?",
      a6: "Absolument ! Que vous voyagiez en solo, en couple, en famille ou en groupe, nos experts locaux conçoivent votre séjour sur-mesure selon vos envies (détente balnéaire à Assinie, trek à Man, patrimoine à Yamoussoukro ou gastronomie abidjanaise) et votre rythme.",
    },
    // Footer
    footer: {
      subtitle: "Conciergerie & Tourisme Réceptif",
      headline_1: "L'excellence du voyage",
      headline_2: "en Terre d'Éburnie.",
      time_header: "Abidjan, Côte d’Ivoire (GMT)",
      start_btn: "Démarrer un projet",
      col1_title: "01 / Destinations",
      view_catalog: "Voir tout le catalogue",
      col2_title: "02 / Services",
      srv_custom: "Circuits 100% personnalisés",
      srv_cars: "Véhicules climatisés récents",
      srv_guides: "Guides certifiés bilingues",
      srv_lodges: "Écolodges & Villas privées",
      srv_about: "À propos d'Akwaba Tours",
      srv_faq: "Foire Aux Questions",
      col3_title: "03 / Conciergerie",
      form_quote: "Formulaire & Devis Sur-Mesure →",
      col4_title: "04 / Disponibilité",
      col4_desc: "Nos conseillers locaux sont à votre écoute pour organiser votre séjour en toute sécurité.",
      season_open: "Saison 2026/2027 ouverte",
      copyright: "Tous droits réservés.",
      privacy: "Confidentialité",
      terms: "Conditions Générales",
      legal: "Mentions Légales",
      country: "Terre d’Éburnie",
      top: "Haut",
    },
    // About Page
    about: {
      tag: "Notre Histoire & Mission",
      hero_title_p1: "Révéler la Grandeur et l'Âme de la",
      hero_title_p2: "Terre d’Éburnie",
      hero_sub: "Akwaba Tours est né d'une conviction profonde : la Côte d'Ivoire possède une richesse culturelle, humaine et naturelle incomparable qui mérite d'être découverte avec respect, passion et excellence.",
      manifesto: "Manifeste",
      manifesto_quote: "« Nous ne faisons pas que guider des pas, nous tissons des liens inoubliables avec un peuple généreux. »",
      hubs_badge: "Siège à Abidjan & Antennes Régionales",
      story_tag: "— Genèse & Philosophie",
      story_title: "Créé par des enfants du pays, pour les voyageurs du monde entier.",
      story_p1: "Fondée par un collectif d'historiens, de guides naturalistes et de passionnés de la Côte d'Ivoire, Akwaba Tours est née de la volonté d'offrir une alternative responsable au tourisme de masse.",
      story_p2: "Des gratte-ciel scintillants du Plateau aux lagunes sauvages d'Assinie-Mafia, des collines brumeuses du Mont Tonkpi aux palais coloniaux de Grand-Bassam, nous créons des itinéraires cousus main qui célèbrent chaque facette de notre patrie.",
      reassurance_1: "100% Capital & Équipe Ivoirienne",
      reassurance_2: "Respect des coutumes & chefferies",
      stat_years_title: "12 Ans",
      stat_years_sub: "D'expertise sur le terrain",
      stat_ethics_title: "Éthique",
      pillars_tag: "Valeurs Fondatrices",
      pillars_title: "Ce qui guide chacun de nos voyages.",
      p1_tag: "Cœur & Valeurs",
      p1_title: "L'Hospitalité Akwaba",
      p1_desc: "En Côte d'Ivoire, « Akwaba » n'est pas qu'un mot de bienvenue : c'est une philosophie de vie. Nous vous accueillons comme un membre de la famille, avec une chaleur et une bienveillance légendaires.",
      p2_tag: "Éco-responsabilité",
      p2_title: "Tourisme Durable & Préservation",
      p2_desc: "Chaque itinéraire est pensé pour protéger les écosystèmes fragiles (forêts primaires, mangroves, faune sacrée) et soutenir directement l'économie des communautés locales.",
      p3_tag: "Authenticité",
      p3_title: "Immersion & Vérité Culturelle",
      p3_desc: "Nous rejetons le tourisme de surface. Nous vous ouvrons les portes des chefferies traditionnelles, des ateliers d'artisans séculaires et des maquis authentiques où bat le vrai cœur d'Éburnie.",
      p4_tag: "Excellence",
      p4_title: "Sécurité & Confort VIP",
      p4_desc: "Tous nos guides sont agréés par le Ministère du Tourisme. Nos véhicules sont récents et climatisés, et nos équipes veillent sur vous 24h/24 pour une tranquillité d'esprit absolue.",
      metrics_tag: "Chiffres & Bilan",
      metrics_title: "Une confiance bâtie voyage après voyage.",
      m1_label: "Voyageurs Émerveillés",
      m1_sub: "Depuis notre création",
      m2_label: "Régions Explorées",
      m2_sub: "Du littoral aux montagnes",
      m3_label: "Taux de Satisfaction",
      m3_sub: "Avis voyageurs certifiés",
      m4_label: "Guides Locaux Experts",
      m4_sub: "Accrédités Ministère du Tourisme",
      guides_tag: "Les Visages d'Akwaba Tours",
      guides_title: "Rencontrez nos guides passionnés.",
      guides_cta: "Réserver avec un guide",
      choose_guide: "Choisir ce guide →",
      cta_tag: "Prêt pour l'Aventure ?",
      cta_title: "Votre séjour d'exception commence ici.",
      cta_sub: "Que vous rêviez d'une escapade balnéaire à Assinie, d'un pèlerinage architectural à Yamoussoukro ou d'une immersion dans les montagnes de Man, notre équipe vous accompagne.",
      cta_btn_custom: "Planifier mon voyage sur-mesure",
      cta_btn_catalog: "Explorer le catalogue",
    },
    // Contact Page
    contact: {
      tag: "Conciergerie & Service Sur-Mesure",
      hero_title_p1: "Commençons à Bâtir Votre Voyage en",
      hero_title_p2: "Terre d’Éburnie",
      hero_sub: "Une question sur une destination ? Une envie d'escapade privée ou un projet de voyage en famille ? Nos conseillers locaux basés à Abidjan vous répondent sous 1 heure.",
      online_status: "Conseillers en ligne",
      whatsapp_title: "Échangez en direct sur WhatsApp",
      whatsapp_sub: "Le moyen le plus rapide pour obtenir un devis personnalisé, poser une question ou valider un itinéraire en quelques minutes.",
      whatsapp_btn: "Discuter sur WhatsApp (+225 07 00...)",
      direct_title: "Nos Coordonnées Directes",
      phone_label: "Téléphone Direct",
      phone_sub: "Ligne fixe Abidjan (8h - 20h GMT)",
      email_label: "Email Conciergerie",
      email_sub: "Réponse garantie en moins de 1h",
      location_label: "Siège Social",
      form_tag: "Devis Sur-Mesure & Échanges",
      form_title: "Parlez-nous de votre projet de voyage",
      form_sub: "Chaque voyage est unique. Donnez-nous quelques détails pour que nous préparions votre séjour idéal.",
      name_field: "Nom complet *",
      phone_field: "Téléphone / WhatsApp *",
      email_field: "Adresse Email *",
      date_field: "Période envisagée",
      dest_field: "Destination Prioritaire",
      type_field: "Type de voyage & Nombre",
      message_field: "Vos envies, souhaits ou questions",
      message_placeholder: "Ex: Nous aimerions passer 3 jours à Assinie en écolodge, puis visiter la Basilique de Yamoussoukro avec un guide privé...",
      submit_btn: "Envoyer ma demande de voyage sur-mesure",
      guarantee: "Vos données sont confidentielles. Devis 100% gratuit et sans engagement sous 1 heure.",
      success_tag: "Demande Reçue avec Succès",
      success_title: "Akwaba cher voyageur !",
      success_sub: "Notre conseiller spécialiste prend en charge votre projet. Vous recevrez une proposition personnalisée d'ici 1 heure.",
      success_whatsapp_btn: "Échanger tout de suite sur WhatsApp",
      success_new_btn: "Nouvelle demande",
      hubs_tag: "Implantation Locale",
      hubs_title: "Présents au plus près de vos étapes.",
      hubs_sub: "Des équipes réactives prêtes à vous accueillir à chaque point névralgique du pays.",
      type_solo: "Voyage Solo (1 personne)",
      type_couple: "En Couple (2 personnes)",
      type_family: "En Famille (3 à 5 personnes)",
      type_friends: "Groupe d'Amis (6+ personnes)",
      type_vip: "Voyage d'Affaires & VIP",
      opt_multi: "Circuit Complet (Plusieurs villes)",
      opt_custom: "Autre / Sur-Mesure Total",
      hub_abidjan_role: "Direction générale & Conciergerie 24/7",
      hub_assinie_role: "Accueil écolodges & transfert nautique",
      hub_bassam_role: "Bureau d'excursions historiques",
      hub_yakro_role: "Guidage Basilique & Centre culturel",
    },
    // Booking Modal
    booking: {
      tag: "Réservation Privée VIP",
      title: "Votre Séjour en Côte d'Ivoire",
      sub: "Remplissez vos préférences, notre équipe ou votre guide vous recontactera sous 1 heure.",
      name_label: "Votre Nom & Prénom *",
      phone_label: "Téléphone / WhatsApp *",
      dest_label: "Destination",
      guests_label: "Nombre de personnes",
      guide_label: "Guide Souhaité",
      date_label: "Date de Voyage Prévue",
      submit: "Confirmer ma Demande de Réservation",
      whatsapp_direct: "Ou réserver directement via WhatsApp →",
      success_tag: "Demande Reçue avec Succès",
      success_title: "Akwaba !",
      success_sub: "Votre demande de réservation a bien été enregistrée. Notre conciergerie ou votre guide prendra contact avec vous d'ici 1 heure.",
      whatsapp_chat_now: "Ouvrir WhatsApp (Réponse Instantanée)",
      close: "Fermer la fenêtre",
      opt_solo: "1 Personne (Solo)",
      opt_duo: "2 Personnes (Duo)",
      opt_small: "3 à 5 Personnes",
      opt_group: "Groupe (6+)",
      opt_best_guide: "Attribuer le meilleur guide disponible",
    },
    // Destinations Page
    destinations_page: {
      tag: "Catalogue Officiel des Destinations",
      title_p1: "Explorez les Joyaux de la",
      title_p2: "Terre d’Éburnie",
      sub: "Des lagunes scintillantes d’Assinie aux sommets majestueux de Man, planifiez votre prochaine escapade en Côte d’Ivoire avec nos experts locaux certifiés.",
      search_placeholder: "Rechercher une ville, une plage, une montagne...",
      cat_all: "Tout",
      cat_beaches: "Plages & Écotourisme",
      cat_culture: "Culture",
      cat_gastronomy: "Gastronomie",
      cat_business: "Business",
      showing_prefix: "Affichage de",
      showing_suffix: "destination(s)",
      clear_search: "Effacer la recherche",
      region_prefix: "Région",
      discover: "Découvrir",
      book: "Réserver",
      empty_title: "Aucune destination trouvée",
      empty_desc: "Aucun résultat ne correspond à votre recherche. Essayez un autre mot-clé ou réinitialisez les filtres.",
      reset_filters: "Réinitialiser les filtres",
      modal_attractions: "Attractions & Expériences Incontournables",
      modal_guide_needed: "Besoin d'un guide certifié pour cette région ?",
      modal_close: "Fermer",
      modal_book: "Réserver",
      modal_best_season: "Meilleure période",
      modal_duration: "Durée recommandée",
      modal_score: "Score voyageurs",
    },
    // Destination Detail Page
    destination_detail: {
      back: "Retour aux destinations",
      home: "Accueil",
      destinations: "Destinations",
      region_prefix: "Région",
      reviews_count: "avis",
      book: "Réserver",
      perspectives_tag: "Perspectives",
      perspectives_title: "Découvrez les temps forts et ambiances de ce lieu.",
      view_prefix: "Vue",
      testimonials_tag: "Témoignages & Expériences",
      testimonials_title_p1: "Ce que nos voyageurs",
      testimonials_title_p2: "ont vécu à",
      verified_visit: "Visite vérifiée",
      highlights_tag: "Ce lieu met à l'honneur...",
    },
  },

  en: {
    // Navigation
    nav: {
      home: 'Home',
      destinations: 'Destinations',
      about: 'About Us',
      contact: 'Contact',
      home_desc: "Adventure in the Land of Eburnie",
      destinations_desc: "Official catalog & bespoke tours",
      about_desc: "Our story & certified local guides",
      contact_desc: "Tailor-made quotes & VIP concierge",
      vip_concierge: "Concierge & VIP Tourism",
      main_nav: "Main Navigation",
      chat_whatsapp: "Chat with a concierge (WhatsApp 24/7)",
      season_open: "2026/2027 Season open 🇨🇮",
      current: "Current",
      time_prefix: "Abidjan GMT :",
    },
    // Hero
    hero: {
      title_p1: "Adventure Awaits in the",
      title_p2: "Land of Eburnie",
      subtitle: "Explore Côte d'Ivoire with passionate guides and signature expeditions. From the sparkling lagoons of Abidjan to the golden beaches of Assinie, through the waterfalls of Man and lively cultural maquis.",
      cta: "Start the Adventure",
      swipe_hint: "Swipe to explore destinations",
    },
    // Who We Are
    who_we_are: {
      tag: "Who We Are",
      headline: "Born from an authentic passion, our mission is to unveil the sheer splendor of the Land of Eburnie. Today, we stand as the gold standard for exceptional travel and expeditions across Côte d'Ivoire.",
      learn_more: "Learn More",
      stat1_num: "5,000+",
      stat1_label: "Enchanted Travelers",
      stat2_title: "Wild Nature Expeditions in Côte d'Ivoire",
      stat3_num: "100%",
      stat3_label: "Guaranteed Satisfaction",
    },
    // Popular Destinations
    popular: {
      tag: "Destinations",
      title: "Most Popular Destinations",
      view_all: "View All Destinations",
      places_visited: "Places Visited",
      abidjan_badge: "Abidjan",
      abidjan_title: "Ébrié Lagoon & Plateau",
      abidjan_places: "05 Places Visited",
      yamoussoukro_badge: "Yamoussoukro",
      yamoussoukro_title: "Basilica of Our Lady of Peace",
      yamoussoukro_places: "03 Places Visited",
      assinie_badge: "Assinie-Mafia",
      assinie_title: "Beaches & Coconut Groves of Assinie",
      assinie_places: "04 Places Visited",
    },
    // Adventures
    adventures: {
      tag: "Tours & Getaways",
      title: "Signature Adventures & Expeditions",
      coverflow_title: "What would you like to experience?",
      item_0_title: "Tropical Jungle Trek",
      item_0_sub: "Mount Tonkpi & Man Waterfalls",
      item_1_title: "Bivouac & Starry Night",
      item_1_sub: "Authentic Nature Wilderness",
      item_2_title: "Canoe Ride on the Lagoon",
      item_2_sub: "Serene Waters of Assinie",
      item_3_title: "Panoramic Aerial View",
      item_3_sub: "Celestial Views of Côte d'Ivoire",
      item_4_title: "Sunset Safari",
      item_4_sub: "Wildlife & Golden Savannah",
      item_5_title: "Historic Grand-Bassam",
      item_5_sub: "Seaside Town & UNESCO Heritage",
    },
    // Reviews
    reviews: {
      tag: "Traveler Reviews",
      title_1: "What our travelers say",
      title_2: "about their journey in Côte d'Ivoire",
      verified_count: "+1,250 verified traveler reviews",
      cat_all: "All Reviews",
      cat_lagoon: "Beaches & Lagoons",
      cat_nature: "Mountains & Nature",
      cat_culture: "Culture & Heritage",
      verified: "Verified Experience",
      cta: "Book Your Own Adventure",
      r1_date: "2 weeks ago",
      r1_circuit: "Assinie & Aby Lagoon Getaway",
      r1_text: "A truly magical stay! The sunset canoe ride in Assinie and the warm hospitality of the Ivorian people touched us deeply. The Akwaba Tours team handled everything with impeccable care and professionalism.",
      r2_date: "3 weeks ago",
      r2_circuit: "Mount Tonkpi Trek & Man Waterfalls",
      r2_text: "Revisiting Côte d'Ivoire with such passionate local guides was an incredible revelation. Crossing the sacred vine bridge and witnessing the misty sunrise over Man's peaks will stay with us forever. 10/10 organization!",
      r3_date: "1 month ago",
      r3_circuit: "Basilica & Splendors of Yamoussoukro",
      r3_text: "Visiting the Basilica of Our Lady of Peace was breathtaking, and the maquis tastings with authentic Garba and fresh alloco were unforgettable! A 100% authentic, secure, and warm immersion. We'll be back without hesitation.",
      r4_date: "3 weeks ago",
      r4_circuit: "Heritage & French Quarter in Bassam",
      r4_text: "The timeless charm of Grand-Bassam completely won us over. Touring the historic mansions of the France Quarter with a passionate guide and having lunch facing the Atlantic waves was a sublime cultural journey.",
    },
    // FAQ
    faq: {
      tag: "Frequently Asked Questions",
      title_1: "Frequently Asked",
      title_2: "Questions",
      subtitle: "Clear and precise answers to the most common questions so you can prepare your adventure in Côte d’Ivoire with complete peace of mind.",
      help_title: "Have a specific question?",
      help_sub: "Speak directly with our Ivorian experts",
      whatsapp_btn: "WhatsApp",
      custom_prompt: "Planning a group journey or a tailor-made stay?",
      custom_cta: "Request a custom quotation",
      q1: "Do I need a visa to travel to Côte d'Ivoire?",
      a1: "Yes, for most travelers outside ECOWAS. The process is straightforward: apply for an e-Visa online (on the official snedai.com platform). You will receive pre-approval by email within 48 hours, and your biometric visa is issued upon arrival at Félix-Houphouët-Boigny International Airport in Abidjan.",
      q2: "What vaccines are required before departure?",
      a2: "Yellow fever vaccination is strictly mandatory and required upon landing with your official international yellow card. Preventive antimalarial treatment and tropical insect repellent are also highly recommended.",
      q3: "What is the best time of year to visit Côte d'Ivoire?",
      a3: "The main dry season, from November to April, offers ideal sunshine for relaxing on the coconut-fringed beaches of Assinie and trekking through the lush green mountains of Man. The climate remains warm and pleasant year-round with continuous cultural richness.",
      q4: "What currency is used and how do payments work?",
      a4: "The official currency is the West African CFA Franc (XOF). International credit cards (Visa, Mastercard) are accepted in major hotels and restaurants in Abidjan. For everyday purchases, local markets, and taxis, cash and mobile money (Wave, Orange Money) are standard.",
      q5: "How are tours and transportation organized on site?",
      a5: "All our transfers and excursions take place in modern, fully air-conditioned, comprehensively insured vehicles driven by vetted local drivers. You are accompanied by certified, bilingual guides, backed by a 24/7 dedicated local concierge.",
      q6: "Can an itinerary be 100% customized?",
      a6: "Absolutely! Whether traveling solo, as a couple, with family, or in a private group, our destination designers tailor every detail to your pace and preferences (Assinie beach relaxation, Man trekking, Yamoussoukro heritage, or Abidjan culinary discovery).",
    },
    // Footer
    footer: {
      subtitle: "Concierge & Inbound Tourism",
      headline_1: "Travel excellence",
      headline_2: "in the Land of Eburnie.",
      time_header: "Abidjan, Côte d’Ivoire (GMT)",
      start_btn: "Start a journey",
      col1_title: "01 / Destinations",
      view_catalog: "View full catalog",
      col2_title: "02 / Services",
      srv_custom: "100% bespoke itineraries",
      srv_cars: "Modern air-conditioned vehicles",
      srv_guides: "Certified bilingual guides",
      srv_lodges: "Ecolodges & Private villas",
      srv_about: "About Akwaba Tours",
      srv_faq: "Frequently Asked Questions",
      col3_title: "03 / Concierge",
      form_quote: "Tailor-Made Quote Form →",
      col4_title: "04 / Availability",
      col4_desc: "Our local travel designers are here to craft your journey in complete serenity.",
      season_open: "2026/2027 Season open",
      copyright: "All rights reserved.",
      privacy: "Privacy Policy",
      terms: "Terms & Conditions",
      legal: "Legal Notice",
      country: "Land of Eburnie",
      top: "Top",
    },
    // About Page
    about: {
      tag: "Our Story & Mission",
      hero_title_p1: "Revealing the Grandeur and Soul of the",
      hero_title_p2: "Land of Eburnie",
      hero_sub: "Akwaba Tours was born from a deep conviction: Côte d'Ivoire possesses an incomparable cultural, human, and natural wealth that deserves to be experienced with reverence, passion, and excellence.",
      manifesto: "Manifesto",
      manifesto_quote: "“We do not merely guide steps; we weave unforgettable bonds with a remarkably generous people.”",
      hubs_badge: "Abidjan Headquarters & Regional Outposts",
      story_tag: "— Origins & Philosophy",
      story_title: "Founded by locals, crafted for travelers from around the world.",
      story_p1: "Founded by a collective of historians, naturalists, and travel enthusiasts, Akwaba Tours was born from the desire to offer an ethical, high-end alternative to mass tourism.",
      story_p2: "From the gleaming skyline of Plateau to the wild lagoons of Assinie-Mafia, from the misty hills of Mount Tonkpi to the colonial mansions of Grand-Bassam, we craft bespoke itineraries celebrating every nuance of our homeland.",
      reassurance_1: "100% Local Capital & Ivorian Team",
      reassurance_2: "Respect for sacred traditions & chiefdoms",
      stat_years_title: "12 Years",
      stat_years_sub: "Of on-the-ground expertise",
      stat_ethics_title: "Ethical",
      pillars_tag: "Core Values",
      pillars_title: "What guides every single one of our journeys.",
      p1_tag: "Heart & Values",
      p1_title: "Akwaba Hospitality",
      p1_desc: "In Côte d'Ivoire, “Akwaba” is more than a welcome: it is a way of life. We welcome you as family, with legendary warmth and benevolence.",
      p2_tag: "Eco-responsibility",
      p2_title: "Sustainable Tourism & Preservation",
      p2_desc: "Every itinerary is designed to protect fragile ecosystems (primary forests, mangroves, sacred wildlife) and directly support local village economies.",
      p3_tag: "Authenticity",
      p3_title: "Immersion & Cultural Truth",
      p3_desc: "We reject surface-level tourism. We open the doors to traditional chiefdoms, centuries-old artisan workshops, and authentic lively maquis where the true heart of Côte d'Ivoire beats.",
      p4_tag: "Excellence",
      p4_title: "Safety & VIP Comfort",
      p4_desc: "All our guides are accredited by the Ministry of Tourism. Our vehicles are modern and fully air-conditioned, and our teams monitor your trip 24/7 for total peace of mind.",
      metrics_tag: "Key Figures & Impact",
      metrics_title: "Trust forged journey after journey.",
      m1_label: "Enchanted Travelers",
      m1_sub: "Since our founding",
      m2_label: "Regions Explored",
      m2_sub: "From coastline to mountains",
      m3_label: "Satisfaction Rate",
      m3_sub: "Certified traveler reviews",
      m4_label: "Expert Local Guides",
      m4_sub: "Ministry of Tourism certified",
      guides_tag: "The Faces of Akwaba Tours",
      guides_title: "Meet our passionate certified guides.",
      guides_cta: "Book with a guide",
      choose_guide: "Choose this guide →",
      cta_tag: "Ready for Adventure?",
      cta_title: "Your exceptional journey begins here.",
      cta_sub: "Whether you dream of a seaside getaway in Assinie, an architectural pilgrimage to Yamoussoukro, or a trek into the mountains of Man, our team is here for you.",
      cta_btn_custom: "Design my bespoke itinerary",
      cta_btn_catalog: "Explore the catalog",
    },
    // Contact Page
    contact: {
      tag: "VIP Concierge & Bespoke Travel",
      hero_title_p1: "Let's Start Crafting Your Journey to the",
      hero_title_p2: "Land of Eburnie",
      hero_sub: "Have a question about a destination? Planning a private retreat or a family expedition? Our Abidjan-based local travel designers reply within 1 hour.",
      online_status: "Advisors Online",
      whatsapp_title: "Chat directly on WhatsApp",
      whatsapp_sub: "The fastest way to get a customized quotation, ask specific questions, or finalize your itinerary in minutes.",
      whatsapp_btn: "Chat on WhatsApp (+225 07 00...)",
      direct_title: "Our Direct Contact Details",
      phone_label: "Direct Phone Line",
      phone_sub: "Abidjan landline (8am - 8pm GMT)",
      email_label: "Concierge Email",
      email_sub: "Guaranteed response within 1 hour",
      location_label: "Headquarters",
      form_tag: "Bespoke Inquiries & Quotes",
      form_title: "Tell us about your dream trip",
      form_sub: "Every journey is unique. Share a few details so we can design your perfect Ivorian stay.",
      name_field: "Full Name *",
      phone_field: "Phone / WhatsApp *",
      email_field: "Email Address *",
      date_field: "Estimated Travel Period",
      dest_field: "Priority Destination",
      type_field: "Travel Type & Group Size",
      message_field: "Your wishes, preferences, or questions",
      message_placeholder: "e.g., We would love to spend 3 days at Assinie ecolodge, then visit the Yamoussoukro Basilica with a private guide...",
      submit_btn: "Send my tailor-made trip inquiry",
      guarantee: "Your data is strictly confidential. 100% free quote with no commitment within 1 hour.",
      success_tag: "Request Received Successfully",
      success_title: "Akwaba dear traveler!",
      success_sub: "Our dedicated destination specialist is now crafting your proposal. You will receive a personalized itinerary within 1 hour.",
      success_whatsapp_btn: "Chat right away on WhatsApp",
      success_new_btn: "Send another inquiry",
      hubs_tag: "Local Presence",
      hubs_title: "Located close to every stage of your trip.",
      hubs_sub: "Responsive local teams ready to welcome you across every key region of the country.",
      type_solo: "Solo Travel (1 person)",
      type_couple: "Couple (2 persons)",
      type_family: "Family (3 to 5 persons)",
      type_friends: "Friends Group (6+ persons)",
      type_vip: "Business & VIP Travel",
      opt_multi: "Complete Tour (Multiple cities)",
      opt_custom: "Other / Fully Bespoke",
      hub_abidjan_role: "Headquarters & 24/7 Concierge",
      hub_assinie_role: "Ecolodges welcome & lagoon transfers",
      hub_bassam_role: "Historical excursion office",
      hub_yakro_role: "Basilica guided tours & cultural center",
    },
    // Booking Modal
    booking: {
      tag: "Private VIP Booking",
      title: "Your Stay in Côte d'Ivoire",
      sub: "Fill in your preferences, our concierge team or assigned guide will reach out within 1 hour.",
      name_label: "Your Full Name *",
      phone_label: "Phone / WhatsApp *",
      dest_label: "Destination",
      guests_label: "Number of Travelers",
      guide_label: "Requested Guide",
      date_label: "Planned Travel Date",
      submit: "Confirm My Booking Request",
      whatsapp_direct: "Or book directly via WhatsApp →",
      success_tag: "Booking Request Received",
      success_title: "Akwaba!",
      success_sub: "Your booking request has been securely recorded. Our concierge team or your assigned guide will reach out within 1 hour.",
      whatsapp_chat_now: "Open in WhatsApp (Instant Reply)",
      close: "Close window",
      opt_solo: "1 Person (Solo)",
      opt_duo: "2 Persons (Duo)",
      opt_small: "3 to 5 Persons",
      opt_group: "Group (6+)",
      opt_best_guide: "Assign the best available guide",
    },
    // Destinations Page
    destinations_page: {
      tag: "Official Destinations Catalog",
      title_p1: "Explore the Jewels of the",
      title_p2: "Land of Eburnie",
      sub: "From the shimmering lagoons of Assinie to the majestic peaks of Man, plan your next getaway to Côte d'Ivoire with our certified local experts.",
      search_placeholder: "Search a city, beach, mountain...",
      cat_all: "All",
      cat_beaches: "Beaches & Ecotourism",
      cat_culture: "Culture",
      cat_gastronomy: "Gastronomy",
      cat_business: "Business",
      showing_prefix: "Displaying",
      showing_suffix: "destination(s)",
      clear_search: "Clear search",
      region_prefix: "Region",
      discover: "Discover",
      book: "Book",
      empty_title: "No destinations found",
      empty_desc: "No results match your search. Try another keyword or reset the filters.",
      reset_filters: "Reset filters",
      modal_attractions: "Must-See Attractions & Experiences",
      modal_guide_needed: "Need a certified guide for this region?",
      modal_close: "Close",
      modal_book: "Book",
      modal_best_season: "Best Season",
      modal_duration: "Recommended Duration",
      modal_score: "Traveler Score",
    },
    // Destination Detail Page
    destination_detail: {
      back: "Back to destinations",
      home: "Home",
      destinations: "Destinations",
      region_prefix: "Region",
      reviews_count: "reviews",
      book: "Book",
      perspectives_tag: "Perspectives",
      perspectives_title: "Discover the highlights and atmospheres of this place.",
      view_prefix: "View",
      testimonials_tag: "Testimonials & Experiences",
      testimonials_title_p1: "What our travelers",
      testimonials_title_p2: "experienced in",
      verified_visit: "Verified visit",
      highlights_tag: "This destination highlights...",
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('akwaba_lang') || 'fr';
  });

  const setLang = (newLang) => {
    const formatted = newLang.toLowerCase();
    setLangState(formatted);
    localStorage.setItem('akwaba_lang', formatted);
  };

  const toggleLang = () => {
    setLang(lang === 'fr' ? 'en' : 'fr');
  };

  // Translation helper function supporting nested paths e.g. t('nav.home')
  const t = (path, fallback = '') => {
    if (!path) return fallback;
    const parts = path.split('.');
    let current = translations[lang] || translations.fr;
    for (const part of parts) {
      if (current && current[part] !== undefined) {
        current = current[part];
      } else {
        // Fallback to French if key missing in English
        let fallbackCurrent = translations.fr;
        for (const fPart of parts) {
          if (fallbackCurrent && fallbackCurrent[fPart] !== undefined) {
            fallbackCurrent = fallbackCurrent[fPart];
          } else {
            return fallback || path;
          }
        }
        return fallbackCurrent;
      }
    }
    return current;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
